# Generated by Django 4.2.17 on 2025-01-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_pharmacy_location_pharmacy_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
