# Generated by Django 4.2.17 on 2025-01-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_pharmacy_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacymanager',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pharmacymanager',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
