# Generated by Django 4.2.17 on 2025-01-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_pharmacymanager_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='city',
        ),
    ]
