# Generated by Django 4.2.17 on 2025-01-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_remove_pharmacymanager_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin'), ('Manager', 'Manager')], default='ADMIN', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pharmacymanager',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin'), ('Manager', 'Manager')], default='guest', max_length=20),
        ),
    ]
